### ISSUE TITLE
Notification in NC app on watch is not dismissed after custom action was selected

### ISSUE THREAD

**Issue by ya-isakov** [matejdro/PebbleNotificationCenter-Android#100]
Hello! I'm using tasker for some custom logic with AutoNotification plugin. I've added two actions to my custom notification. When I get this notification on my watch, I'm pressing on one of actions, but notification is not dismissed on the watch. When I used native notifications, notifications are dismissed properly.

**Comment by matejdro** [comment]
This is intentional. It allows you to keep re-activating actions on the same notification, without creating new one.

After receiving action, just dismiss notification via AutoNotification.

**Comment by ya-isakov** [comment]
I cannot, actually - I'm already disabled Dismiss Upwards for AutoNotification, because I do not want this notification to be on my phone, so tasker is dismissing it right after sending.

**Comment by ya-isakov** [comment]
Anyway, if it's by design, let me close this bug

**Comment by matejdro** [comment]
Before dismissing on the phone, you can store notification parameters (package, it, tag) and use dismiss on pebble Tasker action.

**Comment by ya-isakov** [comment]
Oh, never thought about it.. Thank you for the tip!
