### ISSUE TITLE
XPosed module not working.

### ISSUE THREAD

**Issue by jumper047** [matejdro/PebbleNotificationCenter-Android#106]
I suppose this issue remains open, but maybe..
I ran into an issue with LSposed 1.6.5 - xposed module is active, logs show module activation proceeded as usual, but at the end module just not works - developer connection not toggled on etc. Can you check this issue (of course, if this is not too time-consuming?

**Comment by matejdro** [comment]
Sorry, this has no chance of getting fixed by me. Not using either Xposed, Pebble or NC at the moment.

**Comment by jumper047** [comment]
So it should be fixed by me:)
