### ISSUE TITLE
Pebble Time system apps not listed under "Pebble Apps"

### ISSUE THREAD

**Issue by TheNetStriker** [matejdro/PebbleNotificationCenter-Android#77]
I would like to disable notifications when the Pebble Time Stopwatch and Timer app ist running. Sadly the system apps are not listed under "Pebble Apps". Is it possible to detect if these apps are open? Could you add those apps to the "Pebble Apps" settings?

**Comment by matejdro** [comment]
You can detect them as every other app.

I assume you are rooted? Then you have to use manual mode to detect system apps.

**Comment by TheNetStriker** [comment]
Yes my phone is rooted. Using manual mode I was able to add the missing system apps. Thanks for the hint!
