### ISSUE TITLE
Lift title and subtitle length limit.

### ISSUE THREAD

**Issue by matejdro** [matejdro/PebbleNotificationCenter-Android#79]

**Comment by PeterMinin** [comment]
I found that it can be done by altering `NotificationSendingModule.TITLE_TEXT_LIMIT` and, in the watchapp, the sizes of `char title[31]` and `char subTitle[31]` in NotificationsWindow.c. But maybe it's worth rewriting the watchapp part to allocate the arrays dynamically, like it's done with `char* text`, not to waste too much memory on increased static arrays.

**Comment by matejdro** [comment]
Yeah statically increasing won't do it. Classic Pebble has very low amount of RAM so we can't waste it on title placeholders that will be filled rarely.

My plan is do to it dynamically, but I'm busy at the moment so I'm not exactly sure when I will do it.

**Comment by matejdro** [comment]
https://github.com/matejdro/PebbleNotificationCenter-Android/commit/ce55e4c4f3c6499169275000f5ea05dc2fd0006b
