### ISSUE TITLE
Unnecessary overriding of default app settings

### ISSUE THREAD

**Issue by PeterMinin** [matejdro/PebbleNotificationCenter-Android#80]
First, there is a bug: when the user opens an application's settings, all spinner-time settings get "overridden", even though the user hasn't touched them. This happens because `OnItemSelectedListener` is called on activity creation, even though `setOnItemSelectedListener` is called after `setSelection`. I'm not sure what's the best way to work around this, but I have a suggestion that would fix it as a "side effect".

So, second, we can make an improvement: when the user edits an app-specific setting and sets it to a value that matches the current default, this option should be removed from the app's settings. I think this logic will do the right thing more often than create problems, and at least there will be a way to reset a single setting to default without resetting all of them.

**Comment by matejdro** [comment]
Problem with your suggested approach is that someone might manually change value and then change it back, but then he would not expect it to change again since he set it manually.

**Comment by PeterMinin** [comment]
I realize this is possible, but if he's changing the default, he may as well expect *all* apps that are currently using this option to change. At least this has happened to me.

**Comment by matejdro** [comment]
https://github.com/matejdro/PebbleNotificationCenter-Android/commit/e63bf2b7862ce523961a66e0638680a74f631e60
