### ISSUE TITLE
Deploying watch app to phone causes Pebble to crash

### ISSUE THREAD

**Issue by mozilla2012** [matejdro/PebbleNotificationCenter-Android#83]
As a result, the new watch app cannot be deployed, and thus the whole system doesn't work.

Suggested fixes for now:

1. Re-release the old versions of the watch app and phone app (please!).

2. Fix the crash

3. Enable old watch apps to work with different versions of the phone app (ideal).

Thanks! Currently everybody who updates is without notifications.

If it helps, I'm on a Pebble Steel.

**Comment by mozilla2012** [comment]
Well, apparently you need to have the latest version of the software to update. If you don't have OS 3.0 it does the above crash. You should mention that in the changelog on the playstore so other people don't freak out like I did

**Comment by matejdro** [comment]
Oooh so the problem is that Pebble app crashes, but Pebble Time app works?

**Comment by matejdro** [comment]
I did not realize that. I updated play store changelog to note that. Sorry for troubles.

**Comment by mozilla2012** [comment]
Excellent, thanks!
