### ISSUE TITLE
Extend Custom Vibration to per contact, any app. Including skype, kik, Hangouts, etc.

### ISSUE THREAD

**Issue by ToshieCosed** [matejdro/PebbleNotificationCenter-Android#90]
Please do this.
I'm looking at the source code now and trying to figure out how to do it myself.
I don't think I'll succeed and if I do it won't be the best way of doing it.
Thanks.

**Comment by matejdro** [comment]
That is problematic because notification itself does not contain any info on who contact is. I mean usually it says that in the text, but parsing that would not be very easy.

**Comment by ToshieCosed** [comment]
Can you perhaps add an option to have a list of custom vibration patterns based on an exact match case of the notification title, or an exact match case of the notification text, or on if the notification title contains specific text, or if the notification text contains specific text?

So like say if I open skype in the app list. I'd be able to click an add button and it would add another vibration pattern text field with sub fields being "notification title contains" (checkbox) exact match
"notification text", (checkbox) exact match.
and then let the user decide.
And also an option to "omit special or wildcard characters from parsing for all/any"
in case some apps add special characters to the notification.

Is this possible?

**Comment by matejdro** [comment]
Sorry, that would require quite big code and UI change (If I did that for vibration, I would need to do it for all other settings, otherwise it would look weird).

On the other hand, if you are prepared to use apps that natively supports that (for example some 3rd party SMS apps can specify that), I can add support for that.

**Comment by ToshieCosed** [comment]
Have you heard of Auto Notification? It's a tasker plugin.
Would there be a way to use it to capture a notification within your app, and then have the data fields passed to it?

Another option, could you create a simple API for users to create a new pebble notification?
Allow it to be customized from inside tasker or allow tasker to somehow access it or trigger it?
That would be it too cause then all i'd need is your pebble notify API, and auto notification, I could create a pebble notification with a specific vibration pattern and then set it all up as a list of tasker tasks... uhm this is complicated but i'd spring for it if it worked.

**Comment by matejdro** [comment]
https://dl.dropboxusercontent.com/u/6999250/Dialer/Center/test.apk

This version has new feature that you can enable in per-app option "Use vibration pattern provided by notification". When you check it, you can create notifications with AutoNotification which allows specifying vibration pattern and NC will use that pattern.

**Comment by ToshieCosed** [comment]
Oh my god I tested it and it works atleast within tasker. I think it should
work in call cases then. Thank you so much !!!!
