### ISSUE TITLE
More native visual style

### ISSUE THREAD

**Issue by jumper047** [matejdro/PebbleNotificationCenter-Android#94]
I like functions of your watchapp. But pebble new notifications are beautiful and easy to read, because I can see icon and quickly understand context if notification.
I am own OG Pebble.

**Comment by matejdro** [comment]
Sorry, apps can't use icons in the firmware. And I don't want to add every single icon to my app, it would be huge.

**Comment by jumper047** [comment]
May be some icons by type of app? One for messaging, one for email, etc.

6 июня 2016 г. 22:13:21 GMT+03:00, "Matej Drobnič" <notifications@github.com> пишет:
>Sorry, apps can't use icons in the firmware. And I don't want to add
>every single icon to my app, it would be huge.
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/matejdro/PebbleNotificationCenter-Android/issues/94#issuecomment-224058259

-- 
Простите за краткость, создано в K-9 Mail.

**Comment by matejdro** [comment]
Could you make a mockup on how would this supposed to look?

Layout is a a bit problematic:
- I don't like how native notifications waste entire row at the top just to display an icon
- Pebble does not support text wrapping around images, so I can't just put the icon there and wrap the text around it.

**Comment by jumper047** [comment]
Ok, I'll try to brush something. By the way, is it possible to use font for showing icons? Something like Font Awesome?

7 июня 2016 г. 12:59:35 GMT+03:00, "Matej Drobnič" <notifications@github.com> пишет:
>Could you make a mockup on how would this supposed to look?
>
>Layout is a a bit problematic:
>- I don't like how native notifications waste entire row at the top
>just to display an icon
>- Pebble does not support text wrapping around images, so I can't just
>put the icon there and wrap the text around it.
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/matejdro/PebbleNotificationCenter-Android/issues/94#issuecomment-224235035

-- 
Простите за краткость, создано в K-9 Mail.

**Comment by matejdro** [comment]
Fonts can only display emojis.

**Comment by jumper047** [comment]
Symbols in top half are pictures,  gray background as in original notifications. Cons: 27 pictures with alphabet. Pros: no need in app name string.

7 июня 2016 г. 13:14:06 GMT+03:00, "Matej Drobnič" <notifications@github.com> пишет:
>Fonts can only display emojis.
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/matejdro/PebbleNotificationCenter-Android/issues/94#issuecomment-224238163

-- 
Простите за краткость, создано в K-9 Mail.

**Comment by jumper047** [comment]
http://imgur.com/i1VXgB8
Sorry, forgot it

7 июня 2016 г. 13:14:06 GMT+03:00, "Matej Drobnič" <notifications@github.com> пишет:
>Fonts can only display emojis.
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/matejdro/PebbleNotificationCenter-Android/issues/94#issuecomment-224238163

-- 
Простите за краткость, создано в K-9 Mail.

**Comment by matejdro** [comment]
Isn't the fact that tile text is cut off (like in your messages example) a problem?

**Comment by jumper047** [comment]
I think not if it be optional and text will be user-defined. With this layout i can quickly glance on watch and see what app send the notification. No need to read the text for this.

**Comment by matejdro** [comment]
Sounds reasonable. There is however one additional issue that you will probably not like it: this would represent quite big addition to the code and additional memory requirement to hold that header image.

However, NC's RAM usage is already at the ceiling of the OG Pebble (and Steel), which means that this feature would only be available to Pebble Time users.

**Comment by jumper047** [comment]
:((. Anyway, I think this is good improvement.

**Comment by matejdro** [comment]
Good news! I have managed to squeeze this into Pebble Classic version.

You can test beta here: https://plus.google.com/communities/116982109550451242571 (Links and necessary information is in the sidebar. You don't need to join the community, especially if you don't use G+, but I would appreciate if all feedback would go through the community).
