### ISSUE TITLE
Action on second shake

### ISSUE THREAD

**Issue by jumper047** [matejdro/PebbleNotificationCenter-Android#97]
Is it possible to bind action on second shake? For example, I set up shake to dismiss notification. If I can see screen without light, everything ok.

**Comment by jumper047** [comment]
With last update, it is not so important - i can make roll gesture to enable light.

**Comment by matejdro** [comment]
I'm thinking about it and I understand where you are coming from, but the issue I see is that in daylight or under lights, this would just turn into unnecessary double shake action. And considering watchapp is mostly used in the day (I guess, at least by my usage), this would do more harm than good.

**Comment by jumper047** [comment]
...and not work properly on OG. 
May be it is possible to get data from light sensor, and choose what to do - action or light? (I heard, that pebble have this sensor)

**Comment by matejdro** [comment]
Pebble has this sensor, but unfortunately developers do not have access to it.

**Comment by matejdro** [comment]
Enhancement rejected. Workaround for the issue is enabling gesture mode and using roll to enable backlight and shaking the watch up and down to trigger action.
