### ISSUE TITLE
Customizable backgrounds.

### ISSUE THREAD

**Issue by jumper047** [matejdro/PebbleNotificationCenter-Android#98]
I brush some mockups, may be you like it?
![2016-06-21- 21-56-51-scrot](https://cloud.githubusercontent.com/assets/1407838/16242479/9dceeb84-3803-11e6-8e6b-c623bf2cf941.png)

**Comment by matejdro** [comment]
So you want customizable backgrounds for title and subtitle?

**Comment by jumper047** [comment]
Yes:). I don't like big fonts in header, and different backgrounds helps to separate it from body.

21 июня 2016 г. 22:20:24 GMT+03:00, "Matej Drobnič" <notifications@github.com> пишет:
>So you want customizable backgrounds for title and subtitle?
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/matejdro/PebbleNotificationCenter-Android/issues/98#issuecomment-227543731

-- 
Простите за краткость, создано в K-9 Mail.

**Comment by jumper047** [comment]
Forgot about another moment. Not about background, but also about look. Notification time - can it's font be customizable? And, if possible, with selection for absolute or relative.
![2016-06-21- 22-34-37-scrot](https://cloud.githubusercontent.com/assets/1407838/16243669/76667e30-3809-11e6-9d97-93b9e3734b8d.png)

**Comment by matejdro** [comment]
Actually, notification time is just part of the text at the moment, so it is not customizable.

**Comment by matejdro** [comment]
Here is example on how that looks on actual device:

![pebble_screenshot_2016-06-23_18-53-04](https://cloud.githubusercontent.com/assets/507922/16312158/c5380cac-3973-11e6-8f38-fdc2eac24cd5.png)

As you can see it is not as good as on the mockups. Problem is that Pebble's text formatting system does not report exact same text size as it is displayed (for example you can see there is huge margin at the top and letters cut at the bottom). I can't really fix this by extending the rectangles by static values because those differences vary with the different fonts.

**Comment by jumper047** [comment]
Is it different for every font, or only for font family? There are only 4 or five fonts, May be possible to add constants for every one? 

23 июня 2016 г. 19:58:02 GMT+03:00, "Matej Drobnič" <notifications@github.com> пишет:
>Here is example on how that looks on actual device:
>
>![pebble_screenshot_2016-06-23_18-53-04](https://cloud.githubusercontent.com/assets/507922/16312158/c5380cac-3973-11e6-8f38-fdc2eac24cd5.png)
>
>As you can see it is not as good as on the mockups. Problem is that
>Pebble's text formatting system does not report exact same text size as
>it is displayed (for example you can see there is huge margin at the
>top and letters cut at the bottom). I can't really fix this by
>extending the rectangles by static values because those differences
>vary with the different fonts.
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/matejdro/PebbleNotificationCenter-Android/issues/98#issuecomment-228114005

-- 
Простите за краткость, создано в K-9 Mail.

**Comment by matejdro** [comment]
It is different for every font.

**Comment by jumper047** [comment]
Bad luck. May be add additional size as option?.. For strange peoples like me:)). No good ideas:(. Bad thing is that I had no skills to try it myself.

**Comment by matejdro** [comment]
What do you mean by that?

**Comment by jumper047** [comment]
You said that you need to manually specify the offset for each font. You can add an additional configuration option, which regulates the height of the rectangle. If someone really wants this appearance, he will be able to choose the value of their own.

**Comment by matejdro** [comment]
Sorry, that is a bit too much fidgety, even for my taste. Maybe later when Pebble fixes their font bugs.

**Comment by jumper047** [comment]
@matejdro , can you share share source of watchapp with rectangles?

**Comment by matejdro** [comment]
Here you go: https://github.com/matejdro/PebbleNotificationCenter-Watchapp/tree/text-background-text
