### ISSUE TITLE
Native notifications unstable on Pebble Android app 3.14.0

### ISSUE THREAD

**Issue by ya-isakov** [matejdro/PebbleNotificationCenter-Android#99]
Hello! I've updated to the last version of Pebble Android App, and found that NC native notifications are not working properly. For example, when I'm sending test notification from NC itself, it's shows up after some long delay (3-5 deconds). When I'm pressing "Dismiss on Phone", notification is not really dismissed, and is still shown on the watch.

**Comment by matejdro** [comment]
What happens if you toggle developer connection in the Pebble app?

**Comment by matejdro** [comment]
https://github.com/matejdro/PebbleNotificationCenter-Android/commit/8c8f5bdf0359d1601b8f1d190e7bb6632da0ed42
